# Usa la stessa immagine Python di base per coerenza
FROM python:3.9-slim

# Imposta la cartella di lavoro
WORKDIR /app

# Copia e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice dell'interfaccia utente
COPY ui.py .

# Streamlit, per convenzione, usa la porta 8501
EXPOSE 8501

# Comando specifico per avviare un'applicazione Streamlit
# --server.address=0.0.0.0 permette di accedere al container dall'esterno
CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]