# Usa un'immagine Python ufficiale e leggera come base
FROM python:3.10-slim

# Imposta la cartella di lavoro all'interno del container
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential cmake nano
# Copia e installa le dipendenze per sfruttare la cache di Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia lo script della tua applicazione
COPY app.py .
RUN chmod -R 777 /app
# Crea la cartella che useremo come "mount point" per il volume emptyDir.
# Questa cartella nell'immagine sarà vuota, ma servirà come punto di aggancio
# per la cartella scrivibile fornita da OpenShift.
RUN mkdir /app/model_cache

# Esponi la porta su cui il server Gunicorn ascolterà
EXPOSE 8080
 
# Comando per avviare l'applicazione in modo robusto con Gunicorn.
# --workers 1 è una scelta sicura per un'app che carica un modello pesante in memoria.
# --timeout 120 dà al worker tempo sufficiente per caricare il modello all'avvio.
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "1", "--timeout", "1200", "app:app"]
