# Usa un'immagine Python ufficiale e leggera
FROM python:3.10-slim

# Imposta la cartella di lavoro all'interno del container
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential cmake nano
# Copia e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice dell'applicazione dell'orchestratore
COPY app.py .

# Esponi la porta su cui il server Gunicorn ascolterà
EXPOSE 8080
 
# Comando per avviare l'applicazione in modo robusto
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "2", "--timeout", "300", "app:app"]