# Usa un'immagine Python ufficiale e leggera come base
FROM python:3.10-slim

# Imposta la variabile d'ambiente per la cache dei modelli.
# La libreria sentence-transformers la userà automaticamente.
# Questo percorso deve corrispondere al volume emptyDir su OpenShift.
ENV TRANSFORMERS_CACHE="/app/model_cache"
RUN apt-get update && apt-get install -y build-essential cmake nano
# Imposta la cartella di lavoro all'interno del container
WORKDIR /app

# Copia e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice dell'applicazione per l'embedding
COPY app.py .

# Esponi la porta su cui il server Gunicorn ascolterà
EXPOSE 8080
 
# Comando per avviare l'applicazione con Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "2", "--timeout", "120", "app:app"]